### ISSUE TITLE
storage operator cannot grab the status of a new formatted raw device

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#3341] opened 2021-04-30 13:27 UTC
**Component**:

'storage-operator'

**What happened**:

For some reason sometimes the storage operator cannot grab the metadata of a newly formatted raw block device (UUID, ...)
There is a failed message in the volume objects for phase 2/2
if you do a `blkid` you will see the UUID of the raw block device.

```
blkid
     /dev/nvme4n1: UUID="6eac9fce-98f9-4cb0-8bbb-fc5b95011603" TYPE="ext4"
```

if you do a `lsblk -f` the line for this raw device is empty.

```
lsblk -f
nvme3n1                        ext4                       99e97bee-f980-40f0-a57e-3b4ed6a48c71
nvme4n1
nvme5n1
nvme6n1                        ext4                       3a480516-edef-4f2c-aff9-7485ec601fbf
```

**What was expected**:
I fixed it by rebooting the server but this should be something else to "rescan properly" devices

**Steps to reproduce**
When you have this issue you can reproduce it easily with a simple `mkfs.ext4` on the raw device to see if you fix it or not.

**Resolution proposal** (optional):

**Comment by NickSayer-scality** [comment] 2021-05-05 09:24
I've spent some time trying to reproduce this unaligned state on a LAB DL325 with no success (looping over wipes and mkfs). Not able to put the system in a similar state. As Xavier never encountered this behaviour before and on other hardware. Will try to focus tests on the same HW than the one used by Xavier. As this point, we suspect it might be HW related.
Will update after this additional testing.

**Comment by NicolasT** [comment] 2021-06-22 14:49
Closing since ARTESCA-855 was closed. Can be re-opened if we ever observe this again.

**Comment by TeddyAndrieux** [comment] 2021-12-07 09:06
In order to solve this error where a `blkid` report the UUID of a drive but not `lsblk` nor list on `/dev/disk/by-uuid` we need to refresh disk information using `udevadm trigger --action=changes`

**Closed as completed** 2021-12-09 10:05 UTC
Labels: state:question, topic:storage, topic:operations
