### ISSUE TITLE
Part:1 Upgrading from 2.3 to 2.4 breaks due to salt-authentication issues

### ISSUE THREAD

**Issue by Ebaneck** [scality/metalk8s#1847] opened 2019-10-04 14:52 UTC
See ##1819 for Part:2

**Component**:

'salt', 'kubernetes', 'upgrade'

**What happened**:

 After upgrading from 2.3 to 2.4 the salt API is unable to communicate with the storage operator
and hence we cannot provision any volumes.

This is cause by an old version of `kubernetes_rbac.py` present in the salt cache.

**What was expected**:

- We should be able to create test volumes after an upgrade to metalk8s 2.4.
- Have a working cluster were the Salt api can communicate with the storage operator seamlessly.

**Steps to reproduce**

- upgrade to Metalk8s 2.4
- Check the kubernetes_rbac.py file in the salt master cache,  this file should be the same in a  metalk8s 2.3.  --> This is not what we want. :(

- check salt master logs
```
2019-10-04 14:08:33,469 [salt.auth        :293 ][WARNING ][149] Authentication failure of type "eauth" occurred.
2019-10-04 14:08:33,470 [salt.master      :1985][WARNING ][149] Authentication failure of type "eauth" occurred.
2019-10-04 14:08:34,499 [salt.loaded.ext.auth.kubernetes_rbac:155 ][WARNING ][154] Unknown auth token_type: Bearer
2019-10-04 14:08:35,666 [salt.auth        :293 ][WARNING ][154] Authentication failure of type "eauth" occurred.
2019-10-04 14:08:35,667 [salt.master      :1985][WARNING ][154] Authentication failure of type "eauth" occurred.
2019-10-04 14:08:36,698 [salt.loaded.ext.auth.kubernetes_rbac:155 ][WARNING ][156] Unknown auth token_type: Bearer
2019-10-04 14:08:37,556 [salt.auth        :293 ][WARNING ][156] Authentication failure of type "eauth" occurred.
2019-10-04 14:08:37,558 [salt.master      :1985][WARNING ][156] Authentication failure of type "eauth" occurred.
2019-10-04 14:08:38,590 [salt.loaded.ext.auth.kubernetes_rbac:155 ][WARNING ][140] Unknown auth token_type: Bearer
2019-10-04 14:08:39,817 [salt.auth        :293 ][WARNING ][140] Authentication failure of type "eauth" occurred.
2019-10-04 14:08:39,818 [salt.master      :1985][WARNING ][140] Authentication failure of type "eauth" occurred.
2019-10-04 14:08:40,842 [salt.loaded.ext.auth.kubernetes_rbac:155 ][WARNING ][155] Unknown auth token_type: Bearer
2019-10-04 14:08:41,827 [salt.auth        :293 ][WARNING ][155] Authentication failure of type "eauth" occurred.
2019-10-04 14:08:41,828 [salt.master      :1985][WARNING ][155] Authentication failure of type "eauth" occurred.
2019-10-04 14:08:42,858 [salt.loaded.ext.auth.kubernetes_rbac:155 ][WARNING ][149] Unknown auth token_type: Bearer
2019-10-04 14:08:43,699 [salt.auth        :293 ][WARNING ][149] Authentication failure of type "eauth" occurred.
2019-10-04 14:08:43,701 [salt.master      :1985][WARNING ][149] Authentication failure of type "eauth" occurred.
```

- Finally, check the Storage-operator logs
```
{"level":"error","ts":1570195115.9537094,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"volume-controller","request":"/bootstrap-alertmanager","error":"PrepareVolume failed (env=metalk8s-2.4.0-dev, target=bootstrap, volume=bootstrap-alertmanager): Salt API authentication failed (username=storage-operator, type=Bearer): Salt API failed with code 401: <!DOCTYPE html PUBLIC\n\"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html>\n<head>\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"></meta>\n    <title>401 Unauthorized</title>\n    <style type=\"text/css\">\n    #powered_by {\n        margin-top: 20px;\n        border-top: 2px solid black;\n        font-style: italic;\n    }\n\n    #traceback {\n        color: red;\n    }\n    </style>\n</head>\n    <body>\n        <h2>401 Unauthorized</h2>\n        <p>Could not authenticate using provided credentials</p>\n        <pre id=\"traceback\"></pre>\n    <div id=\"powered_by\">\n      <span>\n        Powered by <a href=\"http://www.cherrypy.org\">CherryPy 5.6.0</a>\n      </span>\n    </div>\n    </body>\n</html>\n","errorVerbose":"Salt API failed with code 401: <!DOCTYPE html PUBLIC\n\"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html>\n<head>\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"></meta>\n    <title>401 Unauthorized</title>\n    <style type=\"text/css\">\n    #powered_by {\n        margin-top: 20px;\n        border-top: 2px solid black;\n        font-style: italic;\n    }\n\n    #traceback {\n        color: red;\n    }\n    </style>\n</head>\n    <body>\n        <h2>401 Unauthorized</h2>\n        <p>Could not authenticate using provided credentials</p>\n        <pre id=\"traceback\"></pre>\n    <div id=\"powered_by\">\n      <span>\n        Powered by <a href=\"http://www.cherrypy.org\">CherryPy 5.6.0</a>\n      </span>\n    </div>\n    </body>\n</html>


```

**Resolution proposal** (optional):

TBD

**Comment by TeddyAndrieux** [comment] 2019-10-04 17:31
As discussed on slack we need to `salt-run metalk8s_saltutil.sync_auth saltenv=metalk8s-<dest_version>` for salt-master in the script of upgrade **and** downgrade, for me we need to do it right after upgrade/downgrade of the bootstrap stuff.
For me we may also sync_all and sync_roster in the salt-master so we have a salt-master really using the destination version.
So in this order (at least the `sync_all` before `sync_auth` as we use our runner to sync_auth as it's not by default in the salt version we use)
```
salt-run saltutil.sync_all saltenv=metalk8s-<dest_version>
salt-run metalk8s_saltutil.sync_auth saltenv=metalk8s-<dest_version>
salt-run saltutil.sync_roster saltenv=metalk8s-<dest_version>
```

**Comment by TeddyAndrieux** [comment] 2019-10-04 17:40
Duplicate of #1819

**Closed as completed by TeddyAndrieux** 2019-10-04 17:40 UTC
Labels: kind:bug
