### ISSUE TITLE
containerd isn't restarted when config changed

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#3129] opened 2021-02-17 21:05 UTC
I have a node on which `containerd` was already installed and running, but with no specific configuration file. When running `bootstrap.sh`, this fails at some point because our fake registry config isn't taken into account.

It appears when we drop a (new) config file for `containerd`, we don't properly restart the service.

**Comment by TeddyAndrieux** [comment] 2021-02-22 15:04
@NicolasT Which version did you try ? 
I think it's fixed in 2.7.0+ (side effect of some rewritting in this commit 5e1a1a22e5e66a842a2be3553274c2bb5a9ccda4 PR #3020 )

**Comment by NicolasT** [comment] 2021-02-23 09:31
2.7.1

**Comment by alexandre-allard** [comment] 2021-03-15 10:44
I can't reproduce this issue on 2.7.3.

I've installed `containerd` prior to launch `bootstrap.sh` and everything went well.
Looking at what's done in the formula, I can't see any issue, we're triggering a restart if the configuration is changed:
```
Configure registry IP in containerd conf:
  file.managed:
    - name: /etc/containerd/config.toml
    - makedirs: true
    - contents: |
        [plugins.cri.registry.mirrors."{{ repo.registry_endpoint }}"]
        endpoint = ["http://{{ registry_ip }}:{{ registry_port }}"]

        [debug]
        level = "{{ 'debug' if metalk8s.debug else 'info' }}"
    - watch_in:
        - service: Ensure containerd running
```
```
Ensure containerd running:
  service.running:
    - name: containerd
    - enable: True
    - init_delay: 2
```

**Comment by NicolasT** [comment] 2021-03-16 16:24
I assume you installed *and started* `containerd` before bootstrap? If so, I guess we can close this as not reproducible :man_shrugging:

**Comment by alexandre-allard** [comment] 2021-03-17 10:52
Yes, that's what I did.

**Comment by alexandre-allard** [comment] 2021-03-17 10:53
Closing this issue as it does not seem to be reproducible on latest versions.

**Closed as completed by alexandre-allard** 2021-03-17 10:53 UTC
Labels: kind:bug, topic:deployment, complexity:easy
