### ISSUE TITLE
Fix kubernetes salt module incompatibility with python-k8s module

### ISSUE THREAD

**Issue by sayf-eddine-scality** [scality/metalk8s#697] opened 2019-03-02 11:52 UTC
https://github.com/kubernetes-client/python/issues/376
as per nicolas suggestion we should monkey-patch the issue or adapt the kubernetes salt module

**Comment by gdemonet** [comment] 2019-04-30 12:53
Duplicate of #991, and as such, closed.

**Closed as completed by gdemonet** 2019-04-30 12:53 UTC
Labels: topic:deployment, kind:debt
