### ISSUE TITLE
kubelet service not restarted when kubeconfig changes

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#765] opened 2019-03-14 15:13 UTC
When `/etc/kubernetes/kubelet.conf` is changed, the `kubelet` service isn't restarted to pick up these changes.

**Comment by NicolasT** [comment] 2019-04-03 12:45
Context: I ran into a situation where Salt modified the file, but after this modification, `kubelet` was not restarted, and I had to do so manually for the changes to be applied.

Can't remember the exact scenario though :-/

**Comment by slaperche-scality** [comment] 2019-04-04 06:57
Given the lack of scenario to reproduce it and the fact that it seems covered in the code (according to @TeddyAndrieux in Slack[1]) maybe we can close it as "Cannot reproduce" (and if it occurs again we can reopen it with more details) ?

----

[1]: 
> For me it's in `salt/metalk8s/kubeadm/init/kubeconfig/kubelet.sls`
> But the state should already restart kubelet
>
> ```yaml
> Restart kubelet:
>  service.running:
>    - name: kubelet
>    - enable: True
>    - watch:
>      - file: Configure kubelet service
>      - file: Ensure CA cert is present
>```

**Comment by NicolasT** [comment] 2019-04-04 07:42
Well, `Configure kubelet service` is about `/etc/systemd/system/kubelet.service.d/10-metalk8s.conf`, and `Ensure CA cert is present` is about `/etc/kubernetes/pki/ca.crt`. However, Kubelet relies on `/var/lib/kubelet/kubeadm-flags.env` for `systemd` configuration (so would require `daemon-reload`), on `/var/lib/kubelet/config.yaml` for its own configuration, on `/etc/kubernetes/kubelet.conf` for its own authentication (the original cause for this ticket), and possibly other files. When those change, the service should pick up those changes (i.e. be restarted) as well, no?

**Comment by slaperche-scality** [comment] 2019-04-04 07:51
Oh, so if I understand we would need to:

```yaml
    - watch:
      - file: Configure kubelet service
      - file: Ensure CA cert is present
+     - file: /var/lib/kubelet/kubeadm-flags.env
+     - file: /var/lib/kubelet/config.yaml
+     - file: /etc/kubernetes/kubelet.conf
```

Because changes to those files should trigger a restart when re-running the state.

**Comment by NicolasT** [comment] 2019-04-04 08:02
Not sure 'it just works' by listing file-paths? But, yeah, something like that.

**Comment by TeddyAndrieux** [comment] 2019-04-04 08:13
But these file should not change at this stage. Or you mean if they got manually edited ?

**Comment by TeddyAndrieux** [comment] 2019-04-04 08:16
Ohh indeed we miss the watch on
```
metalk8s_kubeconfig: Create kubeconf file for kubelet
```

But for `/var/lib/kubelet/kubeadm-flags.env` and `/var/lib/kubelet/config.yaml` we can't here

**Comment by NicolasT** [comment] 2019-04-04 08:18
Maybe we can't here, but then we should elsewhere. If those files are changed (because we change a template, or whatever, and re-deploy) the service must take these changes into account.

**Comment by TeddyAndrieux** [comment] 2019-04-04 08:20
But salt didn't touch these files at this point ? Or maybe we should re-deploy these file like in `kubelet-start` step and likely most of the time do nothing ? 
Yes for me I agree but it's more part of #823 no ? Make sense ?

**Comment by slaperche-scality** [comment] 2019-04-04 11:16
@NicolasT so, for this issue we only tackle `kubelet.conf` and let `kubeadm-flags.env` and `kubelet/config.yaml` for #823?

**Comment by NicolasT** [comment] 2019-04-04 13:06
Not sure how #823 relates to this. If it does, then all `kubelet.conf`, `kubeadm-flags.env` and `config.yaml` are part of the `kubelet` service, I guess, so go together?

Anyway, if this would only handle `kubelet`s `kubeconfig`, then tracking tickets for the others should be created.

**Comment by TeddyAndrieux** [comment] 2019-04-04 13:47
For the moment we have 2 states that edit kubelet configs files.
`kubelet-start` who create/edit `config.yaml` `kubeadm-flags.env` and a service file
`kubelet` (kubeconfig) who create/edit `kubelet.conf` and a service file

#823 it's about group (likely) by services so the state `kubelet-start` and `kubelet` (kubeconfig) will likely be in the same directory and so we can include `kubelet-start` in the `kubelet` (kubeconfig) state and then watch the state that create/edit `kubeadm-flags.env` and `config.yaml`

**Comment by slaperche-scality** [comment] 2019-04-04 15:40
So, to summarize/clarify…

IIUC, for this issue we only need to fix the missing watch for `kubelet.conf`.

- `kubeadm-flags.env` and `config.yaml` are properly handled (watched by `Start and enable kubelet` in `salt/metalk8s/kubeadm/init/kubelet-start/configured.sls`)
- `Restart kubelet` in `salt/metalk8s/kubeadm/init/kubeconfig/kubelet.sl` watch `10-metalk8s.conf` and `/etc/kubernetes/pki/ca.crt`

Now, there is also another issue/feature: restart automatically kubelet when one of those file is modified (potentially out of Salt): this should be tackled in another issue (already exists? or should be created?).

Is that right or did I miss something?

**Comment by NicolasT** [comment] 2019-04-04 15:55
Fair enough if the others are handled.

> potentially out of Salt

No need to handle such scenario. If you modify things 'manually', you're on yourself to restart the service. Even more, likely the change will be overwritten by a later Salt run...

**Closed as completed** 2019-04-05 08:27 UTC
Labels: kind:bug, topic:deployment
