### ISSUE TITLE
Clicking on adding a solution when no solution is imported leads to frozen UI

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#2023] opened 2019-11-06 11:27 UTC
**Component**:

'ui', 'solution'

**What happened**:

After deploying the bootstrap node, one can create Environment in Solution page.
Once the Environment is created, the user is invited to add a solution using the '+' button.
If no solution has been imported and if user click on this button, he will end up with frozen UI:

<img width="1440" alt="Screenshot 2019-11-06 at 12 23 17" src="https://user-images.githubusercontent.com/29035069/68294394-5d5eb580-0090-11ea-9929-18505b055be2.png">

The only way to back on track is to completely reload the page

**What was expected**:

When no solution is deployed, we should either disable the '+' button with a tooltip explaining you should first import some solutions, either have a message saying the same when we click on this button.

**Steps to reproduce**

All in What Happened

**Resolution proposal** (optional):

**Comment by carlito-scality** [comment] 2019-11-06 13:00
duplicate of https://github.com/scality/metalk8s/issues/1937

**Closed as completed by carlito-scality** 2019-11-06 13:00 UTC
Labels: kind:bug, topic:ui, topic:solutions
