### ISSUE TITLE
Expansion test flakiness

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#1305] opened 2019-06-26 12:17 UTC
**Component**: tests, salt

**What happened**:

The expansion test, introduced by #982, show multiple occurences of flaky failures:

- Pods from `monitoring` namespaced are expected to be scheduled on the new node, which may, or may not, be true
- Timeout issues when waiting for running Pods
- One occurence of unreachable target node (`Unable to connect to port 22 on <node-ip>`)

**What was expected**: No flakiness.

**Steps to reproduce**: N/A (flaky)

**Resolution proposal** (optional):

- Handle *infra* Pods differently than static Pods, w.r.t. their expected location
- Increase timeouts
- Add pre-checks (see #1056)

**Comment by jbertran** [comment] 2019-07-01 16:26
Observations so far:

* `monitoring` namespace scheduling: fixed by #1316 
* #1331 detected
* the `node-exporter` timeout bug is unrelated to expansion
* Unable to reproduce more flakies at this time

**Closed as completed** 2019-07-15 12:15 UTC
Labels: kind:bug, topic:tests, topic:flakiness, complexity:medium
